adminUser: admin
# adminPassword: "changeme"

service:
  type: ClusterIP

ingress:
  enabled: false

persistence:
  enabled: false

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

env:
  GF_PATHS_CONFIG: /etc/grafana/custom.ini

extraConfigmapMounts:
  - name: grafana-custom-ini
    mountPath: /etc/grafana/custom.ini
    subPath: grafana.ini
    configMap: grafana-custom-ini
    readOnly: true
    
